# Generated by Django 3.2.4 on 2021-07-08 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0004_auto_20210707_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='prerequisites',
        ),
    ]
