# Generated by Django 3.2.4 on 2021-07-15 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0008_auto_20210708_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.chapter')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.course')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.chapterpage')),
            ],
        ),
    ]
